In [183]:
import ast
import pandas as pd
from statistics import mean

In [184]:
sentence_df = pd.read_csv('sentence_df_1606.csv')

In [185]:
sentence_df

,tuples,article_id,sentences,relation,publishedAt,merger_or_acq,keywords,mentions,relations,wikidata,lowered_head,lowered_tail,companies_deal,final_company_deal,general_questions,head_questions,tail_questions
0,"('apple_inc.', 'considering_acq', 'netflix', '...",1.0,There is a 40% likelihood that Apple will acqu...,considering_acq,2018-01-01T09:04:47Z,Acq,acquire,"[('Citi', 'Org'), ('Apple', 'Bidder'), ('Netfl...",['40% likelihood'],True,apple_inc.,netflix,"['apple_inc.', 'netflix']",apple_inc._netflix,"((""What's the deal between apple_inc. and netf...",NaN,NaN
1,"('apple_inc.', 'success_acq', 'buddybuild', '2...",56.0,Shutterstock A Vancouver company called Buddyb...,success_acq,2018-01-02T21:03:33Z,Acq,acquired,"[('Apple', 'Bidder'), ('Shutterstock', 'Org'),...",['been acquired'],False,apple_inc.,buddybuild,"['apple_inc.', 'buddybuild']",apple_inc._buddybuild,"((""What's the deal between apple_inc. and budd...",{'before': [('Who owns Imagination Technologie...,"{'before': [], 'after': []}"
2,"('apple_inc.', 'success_acq', 'beats music', '...",177.0,"Of course, Apple rarely makes big acquisitions...",success_acq,2018-01-04T18:43:29Z,Acq,acquisition,"[('Apple', 'Bidder'), ('acquisitions', 'succes...",['acquisitions'],False,apple_inc.,beats music,"['apple_inc.', 'beats music']",apple_inc._beats music,"((""What's the deal between apple_inc. and beat...",{'before': [('Who owns Imagination Technologie...,"{'before': [], 'after': []}"
3,"('apple_inc.', 'expecting_acq', 'shazam', '201...",1542.0,The European Commission is one such regulatory...,expecting_acq,2018-02-06T17:43:48Z,Acq,acquisition,"[('Shazam', 'Target'), ('planned acquisition',...",['planned acquisition'],True,apple_inc.,shazam,"['apple_inc.', 'shazam']",apple_inc._shazam,"((""What's the deal between apple_inc. and shaz...",NaN,NaN
4,"('apple_inc.', 'success_acq', 'beats_electroni...",1758.0,"Apple's largest acquisition to date was Beats,...",success_acq,2018-02-11T13:48:07Z,Acq,acquisition,"[('largest acquisition to date', 'success'), (...",['largest acquisition to date'],True,apple_inc.,beats_electronics,"['apple_inc.', 'beats_electronics']",apple_inc._beats_electronics,"((""What's the deal between apple_inc. and beat...",{'before': [('Who owns Imagination Technologie...,{'before': [('Does Apple Inc. (Q312) owns appl...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5732,"('hyundai_motor_company', 'success_acq', 'bost...",53082.0,Hyundai has now completed its $1.1 billion USD...,success_acq,2021-06-22T04:56:36Z,Acq,acquisition,"[('Hyundai', 'Bidder'), ('completed', 'success...","['completed', 'acquisition']",False,hyundai_motor_company,boston_dynamics,"['boston_dynamics', 'hyundai_motor_company']",hyundai_motor_company_boston_dynamics,"((""What's the deal between hyundai_motor_compa...",{'before': [('Does Hyundai Mobis (Q497534) own...,{'before': [('Does SoftBank (Q201653) owns hyu...
5733,"('tpg_(isp)', 'success_merger', 'vodafone_hutc...",11627.0,The merger of TPG Telecom and Vodafone Hutchis...,success_merger,2018-08-29T18:46:12Z,Merger,merger,"[('TPG Telecom', 'Bidder'), ('Vodafone Hutchis...",['merger'],True,tpg_(isp),vodafone_hutchison_australia,"['tpg_(isp)', 'vodafone_hutchison_australia']",tpg_(isp)_vodafone_hutchison_australia,"((""What's the deal between tpg_(isp) and vodaf...","{'before': [], 'after': []}",{'before': [('Does CK Hutchison Holdings (Q195...
5734,"('illumina,_inc.', 'success_acq', 'grail', '20...",40240.0,Cancer detection startupÂ Grail will be acquire...,success_acq,2020-09-21T17:43:52Z,Acq,acquire,"[('Grail', 'Target'), ('will be acquired', 'su...",['will be acquired'],False,"illumina,_inc.",grail,"['grail', 'illumina,_inc.']","illumina,_inc._grail","((""What's the deal between illumina,_inc. and ...",{'before': [('Who does Advanced Liquid Logic (...,"{'before': [], 'after': []}"
5735,"('blackberry_limited', 'success_acq', 'cylance...",14991.0,"â November 16, 2018 â BlackBerry Limited (NYSE...",success_acq,2018-11-16T12:18:39Z,Acq,acquire,[('entered into a definitive agreement to whol...,['entered into a definitive agreement to wholl...,True,blackberry_limited,cylance,"['blackberry_limited', 'cylance']",blackberry_limited_cylance,"((""What's the deal between blackberry_limited ...",{'before': [('Who owns BlackBerry (Q84790062) ...,"{'before': [], 'after': []}"
5736,"('philip_morris_international', 'success_merge...",26880.0,(Reuters) - Marlboro maker Philip Morris Inter...,success_merger,2019-08-27T22:36:56Z,Merger,merger,"[('Reuters', 'Org'), ('Philip Morris Internati...",['following its 2008'],False,philip_morris_international,altria,"['altria', 'philip_morris_international']",philip_morris_international_altria,"((""What's the deal between philip_morris_inter...","{'before': [('Who does PMFTC, Inc. (Q7119736) ...",{'before': [('Who owns Parliament (Q1148560) b...

In [186]:
# Number of sentences per relation
sentence_df['relation'].value_counts()

success_acq           2760
expecting_acq         1062
expecting_merger       597
success_merger         552
considering_acq        333
considering_merger     241
terminated_merger      138
terminated_acq          54
Name: relation, dtype: int64

In [187]:
res = []
for entity in sentence_df['lowered_head'].unique():
    data = sentence_df[sentence_df['lowered_head'] == entity]
    res.append(data['final_company_deal'].nunique())

In [188]:
print(mean(res))
print(max(res))
print(min(res))

1.8257191201353637
74
1

### Average questions

In [189]:
sentence_df['general_questions'] = sentence_df['general_questions'].apply(lambda x: ast.literal_eval(x))

In [190]:
data = sentence_df[~sentence_df['head_questions'].isna()]; data
data.reset_index(drop = True, inplace = True)

In [191]:
data['head_questions'] = data['head_questions'].apply(lambda x: ast.literal_eval(x))
data['tail_questions'] = data['tail_questions'].apply(lambda x: ast.literal_eval(x))

<ipython-input-191-9feda848cf66>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['head_questions'] = data['head_questions'].apply(lambda x: ast.literal_eval(x))
<ipython-input-191-9feda848cf66>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tail_questions'] = data['tail_questions'].apply(lambda x: ast.literal_eval(x))

In [192]:
data['head_before'] = data['head_questions'].apply(lambda x: x['before'])
data['head_after'] = data['head_questions'].apply(lambda x: x['after'])

data['tail_before'] = data['tail_questions'].apply(lambda x: x['before'])
data['tail_after'] = data['tail_questions'].apply(lambda x: x['after'])

<ipython-input-192-bc1e5eb78e89>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['head_before'] = data['head_questions'].apply(lambda x: x['before'])
<ipython-input-192-bc1e5eb78e89>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['head_after'] = data['head_questions'].apply(lambda x: x['after'])
<ipython-input-192-bc1e5eb78e89>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tail_before'] = data['tail_questions'].apply(lambda x: x['before'])
<ipython-input-192-bc1e5eb78e89>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tail_after'] = data['tail_questions'].apply(lambda x: x['after'])

In [193]:
data

,tuples,article_id,sentences,relation,publishedAt,merger_or_acq,keywords,mentions,relations,wikidata,...,lowered_tail,companies_deal,final_company_deal,general_questions,head_questions,tail_questions,head_before,head_after,tail_before,tail_after
0,"('apple_inc.', 'success_acq', 'buddybuild', '2...",56.0,Shutterstock A Vancouver company called Buddyb...,success_acq,2018-01-02T21:03:33Z,Acq,acquired,"[('Apple', 'Bidder'), ('Shutterstock', 'Org'),...",['been acquired'],False,...,buddybuild,"['apple_inc.', 'buddybuild']",apple_inc._buddybuild,((What's the deal between apple_inc. and buddy...,{'before': [('Who owns Imagination Technologie...,"{'before': [], 'after': []}",[(Who owns Imagination Technologies (Q1119662)...,[(Who owns Imagination Technologies (Q1119662)...,[],[]
1,"('apple_inc.', 'success_acq', 'beats music', '...",177.0,"Of course, Apple rarely makes big acquisitions...",success_acq,2018-01-04T18:43:29Z,Acq,acquisition,"[('Apple', 'Bidder'), ('acquisitions', 'succes...",['acquisitions'],False,...,beats music,"['apple_inc.', 'beats music']",apple_inc._beats music,((What's the deal between apple_inc. and beats...,{'before': [('Who owns Imagination Technologie...,"{'before': [], 'after': []}",[(Who owns Imagination Technologies (Q1119662)...,[(Who owns Imagination Technologies (Q1119662)...,[],[]
2,"('apple_inc.', 'success_acq', 'beats_electroni...",1758.0,"Apple's largest acquisition to date was Beats,...",success_acq,2018-02-11T13:48:07Z,Acq,acquisition,"[('largest acquisition to date', 'success'), (...",['largest acquisition to date'],True,...,beats_electronics,"['apple_inc.', 'beats_electronics']",apple_inc._beats_electronics,((What's the deal between apple_inc. and beats...,{'before': [('Who owns Imagination Technologie...,{'before': [('Does Apple Inc. (Q312) owns appl...,[(Who owns Imagination Technologies (Q1119662)...,[(Who owns Imagination Technologies (Q1119662)...,[(Does Apple Inc. (Q312) owns apple_inc. befor...,[(Does Apple Inc. (Q312) owns apple_inc. after...
3,"('apple_inc.', 'success_acq', 'texture_(app)',...",3029.0,"This week, Apple announced its latest acquisit...",success_acq,2018-03-12T19:32:01Z,Acq,acquisition,"[('Apple', 'Bidder'), ('Next Issue Media', 'Ta...",['announced its latest acquisition'],False,...,texture_(app),"['apple_inc.', 'texture_(app)']",apple_inc._texture_(app),((What's the deal between apple_inc. and textu...,{'before': [('Who owns Imagination Technologie...,"{'before': [], 'after': []}",[(Who owns Imagination Technologies (Q1119662)...,[(Who owns Imagination Technologies (Q1119662)...,[],[]
4,"('apple_inc.', 'success_acq', 'akonia_holograp...",11675.0,News of Apple's acquisition of Akonia comes ho...,success_acq,2018-08-30T07:47:11Z,Acq,acquisition,"[('Apple', 'Bidder'), ('acquisition', 'success...",['acquisition'],False,...,akonia_holographics_(united_states),"['akonia_holographics_(united_states)', 'apple...",apple_inc._akonia_holographics_(united_states),((What's the deal between apple_inc. and akoni...,{'before': [('Who owns Imagination Technologie...,"{'before': [], 'after': []}",[(Who owns Imagination Technologies (Q1119662)...,[(Who owns Imagination Technologies (Q1119662)...,[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3307,"('hyundai_motor_company', 'success_acq', 'bost...",53082.0,Hyundai has now completed its $1.1 billion USD...,success_acq,2021-06-22T04:56:36Z,Acq,acquisition,"[('Hyundai', 'Bidder'), ('completed', 'success...","['completed', 'acquisition']",False,...,boston_dynamics,"['boston_dynamics', 'hyundai_motor_company']",hyundai_motor_company_boston_dynamics,((What's the deal between hyundai_motor_compan...,{'before': [('Does Hyundai Mobis (Q497534) own...,{'before': [('Does SoftBank (Q201653) owns hyu...,[(Does Hyundai Mobis (Q497534) owns hyundai_mo...,[(Does Hyundai Mobis (Q497534) owns hyundai_mo...,[(Does SoftBank (Q201653) owns hyundai_motor_c...,[(Does SoftBank (Q201653) owns hyundai_motor_c...
3308,"('tpg_(isp)', 'success_merger', 'vodafone_hutc...",11627.0,The merger of TPG Telecom and Vodafone Hutchis...,success_merger,2018-08-29T18:46:12Z,Merger,merger,"[('TPG Telecom', 'Bidder'), ('Vodafone Hutchis...",['merger'],True,...,vodafone_hutchison_australia,"['tpg_(isp)', 'vodafone_hutchison_australia']",tpg_(isp)_vodafone_hutchison_australia,((What's the deal between tpg_(isp) and vodafo...,"{'before': [], 'after': []}",{'before': [('Does CK Hutchison Holdings (Q195...,[],[],[(Does CK Hutchison Holdings (Q19548352) owns ...,[(Does CK Hutchison Holdings (Q19548352) owns ...
3309,"('illumina,_inc.', 'success_acq', 'grail', '20...",40240.0,Cancer detection startupÂ Grail will be acquire...,success_acq,2020-09-21T17:43:52Z,Acq,acquire,"[('Grail', 'Target'), ('will be acquired', 'su...",['will be acquired'],False,...,grail,"['grail', 'illumina,_inc.']","illumina,_inc._grail","((What's the deal between illumina,_inc. and g...",{'before': [('Who does Advanced Liquid Logic (...,"{'before': [], 'after': []}",[(Who does Advanced Liquid Logic (Q30253440) b...,[(Who does Advanced Liquid Logic (Q30253440) b...,[],[]
3310,"('blackberry_limited', 'success_acq', 'cylance...",14991.0,"â November 16, 2018 â BlackBerry Limited (NYSE...",success_acq,2018-11-16T12:18:39Z,Acq,acquire,[('entered into a definitive agreement to whol...,['entered into a definitive agreement to wholl...,True,...,cylance,"['blackberry_limited', 'cylance']",blackberry_limited_cylance,((What's the deal between blackberry_limited a...,{'before': [('Who owns BlackBerry (Q84790062) ...,"{'before': [], 'after': []}",[(Who owns BlackBerry (Q84790062) before the l...,[(Who owns BlackBerry (Q84790062) after the la...,[],[]
3311,"('philip_morris_international', 'success_merge...",26880.0,(Reuters) - Marlboro maker Philip Morris Inter...,success_merger,2019-08-27T22:36:56Z,Merger,merger,"[('Reuters', 'Org'), ('Philip Morris Internati...",['following its 2008'],False,...,altria,"['altria', 'philip_morris_international']",philip_morris_international_altria,((What's the deal between philip_morris_intern...,"{'before': [('Who does PMFTC, Inc. (Q7119736) ...",{'before': [('Who owns Parliament (Q1148560) b...,"[(Who does PMFTC, Inc. (Q7119736) belong to be...","[(Who does PMFTC, Inc. (Q7119736) belong to af...",[(Who owns Parliament (Q1148560) before the la...,[(Who owns Parliament (Q1148560) after the lat...

In [194]:
# calculate length of head questions and tail questions before and after (the average probably)
print(mean([len(x) for x in list(data['head_before'])]))
print(max([len(x) for x in list(data['head_before'])]))
print(min([len(x) for x in list(data['head_before'])]))
print('-----------------------------------')
print(mean([len(x) for x in list(data['head_after'])]))
print(max([len(x) for x in list(data['head_after'])]))
print(min([len(x) for x in list(data['head_after'])]))
print('-----------------------------------')
print(mean([len(x) for x in list(data['tail_before'])]))
print(max([len(x) for x in list(data['tail_before'])]))
print(min([len(x) for x in list(data['tail_before'])]))
print('-----------------------------------')
print(mean([len(x) for x in list(data['tail_after'])]))
print(max([len(x) for x in list(data['tail_after'])]))
print(min([len(x) for x in list(data['tail_after'])]))

15.318840579710145
289
0
-----------------------------------
15.318840579710145
289
0
-----------------------------------
1.013586956521739
195
0
-----------------------------------
1.013586956521739
195
0

### Knowledge Graph

In [195]:
tkg_df = pd.read_csv('tkg_df_0606.csv')

In [196]:
tkg_df

,head_entity,relation,tail_entity,start_date,end_date
0,apple_inc.,owner of (P1830),Imagination Technologies (Q1119662),2018-01-01 00:00:00+00:00,NaN
1,ford_motor_company,business division (P199),Otosan (Q1790346),2018-01-01 00:00:00+00:00,NaN
2,ford_motor_company,business division (P199),Ford Sollers (Q16993649),2018-01-01 00:00:00+00:00,NaN
3,ford_motor_company,board member (P3320),Kimberly Casiano (Q6409905),2018-01-01 00:00:00+00:00,NaN
4,ford_motor_company,board member (P3320),Anthony Earley (Q109562317),2018-01-01 00:00:00+00:00,NaN
...,...,...,...,...,...
16544,nxlv,success_acq,nexliving,2021-06-30 14:00:00+00:00,NaN
16545,trackhouse racing,expecting_merger,nascar,2021-06-30 14:05:26+00:00,NaN
16546,nuevopak,success_acq,nuevopak global limited,2021-06-30 14:20:36+00:00,NaN
16547,sb energy,success_merger,adani green energy limite,2021-06-30 15:06:41+00:00,NaN
16548,microsoft,expecting_acq,at&amp;ts,2021-06-30 15:12:32+00:00,NaN

In [197]:
tkg_df[tkg_df['start_date'] == "2018-01-01 00:00:00+00:00"]

,head_entity,relation,tail_entity,start_date,end_date
0,apple_inc.,owner of (P1830),Imagination Technologies (Q1119662),2018-01-01 00:00:00+00:00,NaN
1,ford_motor_company,business division (P199),Otosan (Q1790346),2018-01-01 00:00:00+00:00,NaN
2,ford_motor_company,business division (P199),Ford Sollers (Q16993649),2018-01-01 00:00:00+00:00,NaN
3,ford_motor_company,board member (P3320),Kimberly Casiano (Q6409905),2018-01-01 00:00:00+00:00,NaN
4,ford_motor_company,board member (P3320),Anthony Earley (Q109562317),2018-01-01 00:00:00+00:00,NaN
...,...,...,...,...,...
8313,comcast,board member (P3320),Madeline Bell (Q108809595),2018-01-01 00:00:00+00:00,NaN
8314,roche,subsidiary (P355),Roche (United States) (Q29123180),2018-01-01 00:00:00+00:00,NaN
8315,comcast,board member (P3320),Jeff Honickman (Q21551980),2018-01-01 00:00:00+00:00,NaN
8316,roche,subsidiary (P355),Chemische Werke Grenzach (Q107138841),2018-01-01 00:00:00+00:00,NaN
8317,roche,subsidiary (P355),Roche (Czechia) (Q43896251),2018-01-01 00:00:00+00:00,NaN

In [198]:
tkg_df[tkg_df['start_date'] != "2018-01-01 00:00:00+00:00"]

,head_entity,relation,tail_entity,start_date,end_date
8318,apple_inc.,considering_acq,netflix,2018-01-01 09:04:47+00:00,NaN
8319,prestige_group,success_acq,capitaland,2018-01-01 12:46:26+00:00,NaN
8320,bd_(company),success_acq,bard,2018-01-02 00:00:00+00:00,NaN
8321,bhi,success_merger,marcventure,2018-01-02 09:09:57+00:00,NaN
8322,h.j. heinz,success_merger,kraft_foods,2018-01-02 10:15:00+00:00,NaN
...,...,...,...,...,...
16544,nxlv,success_acq,nexliving,2021-06-30 14:00:00+00:00,NaN
16545,trackhouse racing,expecting_merger,nascar,2021-06-30 14:05:26+00:00,NaN
16546,nuevopak,success_acq,nuevopak global limited,2021-06-30 14:20:36+00:00,NaN
16547,sb energy,success_merger,adani green energy limite,2021-06-30 15:06:41+00:00,NaN
16548,microsoft,expecting_acq,at&amp;ts,2021-06-30 15:12:32+00:00,NaN

In [199]:
tkg_df[tkg_df['start_date'] == "2018-01-01 00:00:00+00:00"]['end_date'].isna().value_counts()

# 6996 facts no change
# 1322 facts change

True     6996
False    1322
Name: end_date, dtype: int64

In [200]:
tkg_df['head_entity'].nunique()

3927

In [201]:
tkg_df['tail_entity'].nunique()

13412

In [202]:
len(list(set(list(tkg_df['head_entity'].unique()) + list(tkg_df['tail_entity'].unique()))))

16068

In [203]:
tkg_df['relation'].value_counts()

subsidiary (P355)           4197
owner of (P1830)            3443
success_acq                 2983
expecting_acq               1285
success_merger              1085
owned by (P127)              899
expecting_merger             778
board member (P3320)         729
considering_acq              430
considering_merger           302
business division (P199)     173
terminated_merger            151
terminated_acq                94
Name: relation, dtype: int64

### Entities List

In [204]:
entities_list = pd.read_csv('entities_list_0606.csv')

In [205]:
entities_list = entities_list[~entities_list['lowered_entity_names'].isna()]
entities_list.reset_index(drop = True, inplace = True)

In [206]:
entities_list['eda_data'] = entities_list['eda_data'].apply(lambda x: ast.literal_eval(x))

In [207]:
flat_list = [x for xs in list(entities_list['eda_data']) for x in xs]

In [208]:
eda_data_df = pd.DataFrame(flat_list, columns=['entity', 'attributes', 'values', 'start_date']); eda_data_df

,entity,attributes,values,start_date
0,apple_inc.,industry (P452),software industry (Q880371),2018-01-01T00:00:00Z
1,apple_inc.,industry (P452),consumer electronics (Q581105),2018-01-01T00:00:00Z
2,apple_inc.,industry (P452),digital distribution (Q269415),2018-01-01T00:00:00Z
3,apple_inc.,industry (P452),electronics (Q11650),2018-01-01T00:00:00Z
4,apple_inc.,industry (P452),information technology (Q11661),2018-01-01T00:00:00Z
...,...,...,...,...
10050,complex_networks,country (P17),United States of America (Q30),2018-01-01T00:00:00Z
10051,bluepoint_(romania),country (P17),Romania (Q218),2018-01-01T00:00:00Z
10052,wickr,industry (P452),software industry (Q880371),2018-01-01T00:00:00Z
10053,tervita,industry (P452),petroleum industry (Q862571),2018-01-01T00:00:00Z
10054,tervita,inception (P571),+1979-00-00T00:00:00Z,2018-01-01T00:00:00Z

In [209]:
eda_data_df[eda_data_df['attributes'] == 'industry (P452)']['values'].value_counts()[:10]

financial service (Q837171)                179
telecommunications industry (Q25245117)     84
retail (Q126793)                            75
pharmaceutical industry (Q507443)           69
petroleum industry (Q862571)                65
software industry (Q880371)                 65
Finanzwesen (Q1416657)                      61
banking industry (Q806718)                  56
automotive industry (Q190117)               49
video game industry (Q941594)               49
Name: values, dtype: int64

In [210]:
eda_data_df[eda_data_df['attributes'] == 'country (P17)']['values'].value_counts()[:10]

United States of America (Q30)       1005
United Kingdom (Q145)                 124
India (Q668)                          108
Germany (Q183)                         77
Canada (Q16)                           66
Japan (Q17)                            65
France (Q142)                          60
People's Republic of China (Q148)      39
Australia (Q408)                       34
Italy (Q38)                            33
Name: values, dtype: int64

In [211]:
eda_data_df[eda_data_df['attributes'] == 'stock exchange (P414)']['values'].value_counts()[:10]

New York Stock Exchange (Q13677)              507
NASDAQ (Q82059)                               348
London Stock Exchange (Q171240)                97
OTC Markets Group (Q1930860)                   69
Tokyo Stock Exchange (Q217475)                 68
Toronto Stock Exchange (Q818723)               58
Australian Securities Exchange (Q732670)       57
National Stock Exchange of India (Q638740)     45
Hong Kong Stock Exchange (Q496672)             38
Frankfurt Stock Exchange (Q151139)             28
Name: values, dtype: int64

In [212]:
eda_data_df[eda_data_df['attributes'] == 'part of (P361)']['values'].value_counts()[:10]

S&P 500 (Q242345)                         247
DivDAX (Q1230458)                          45
FTSE 100 Index (Q466496)                   41
Nasdaq-100 (Q507306)                       37
CDAX (Q874430)                             31
Deutscher Aktien indeX (DAX) (Q155718)     31
Dow Jones Industrial Average (Q180816)     26
MDAX (Q595622)                             23
CAC 40 (Q648828)                           20
EURO STOXX 50 (Q981010)                    16
Name: values, dtype: int64

In [213]:
eda_data_df['attributes'].value_counts()

industry (P452)          2403
inception (P571)         2389
country (P17)            2010
stock exchange (P414)    1551
founded by (P112)        1065
part of (P361)            637
Name: attributes, dtype: int64

2018 data
---------
No. articles: 16750  
No. sentences: 47704


2019 data
---------
No. articles: 14448  
No. sentences: 44635


2020 data
---------
No. articles: 13480  
No. sentences: 39379


2021 data
---------
No. articles: 9008  
No. sentences: 23995